services:
    eliza:
        command: ["pnpm", "start", "--character=./characters/eliza.character.json"]
        build:
            context: .
            dockerfile: Dockerfile
        stdin_open: true
        tty: true
        volumes:
            - ./data:/app/data
        environment:
            - DISCORD_APPLICATION_ID=
            - DISCORD_API_TOKEN=
            - GROK_API_KEY=
            - ELEVENLABS_XI_API_KEY=
            - ELEVENLABS_MODEL_ID=eleven_multilingual_v2
            - ELEVENLABS_VOICE_ID=21m00Tcm4TlvDq8ikWAM
        ports:
            - "3000:3000"
        restart: always
